"""add refresh token family id

Revision ID: 5c974eefac94
Revises: 8e3d99aed6a7
Create Date: 2026-08-19 15:39:48.232562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c974eefac94'
down_revision: Union[str, Sequence[str], None] = '8e3d99aed6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_family_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_token_family_id'), 'refresh_tokens', ['token_family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_family_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'token_family_id')
    # ### end Alembic commands ###
